// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TDD","status":true,"description":"1.0.7 Plugin Commands for binding pictures to the map and/or changing what layer they're drawn on.","parameters":{}}
];
